config/routes.rb
class SubdomainRequired
  def self.matches?(request)
    request.subdomain.present? request.subdomain != "www"
  end
end

Rails.application.routes.draw do

  devise_for :users
  root to: 'welcome#index'
  resource :account, only: [:new, :create]

  constraints SubdomainRequired do
    root to: 'dashboards#show', as: 'subdomain_root'
  end

end

app/models/account.rb
class Account < ActiveRecord::Base
	validates :name, :subdomain, presence: true
	validates :subdomain,
          format: { with: /\A[a-z][a-z0-9\-]+[a-z0-9]\Z/ },
          uniqueness: true
  has_many :memberships, dependent: :destroy
	has_many :users, through: :memberships
	has_one :owner_membership, -> { where(role: 'owner') }, class_name: 'Membership'
  has_one :owner, through: :owner_membership, source: :user, class_name: 'User'
  accepts_nested_attributes_for :owner
end

app/models/membership.rb
class Membership < ActiveRecord::Base
  belongs_to :account
  belongs_to :user

	validates :account, :user, presence: true
	validates :role, inclusion: { in: SYSTEM_ROLES }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

	has_many :memberships, dependent: :destroy
	has_many :accounts, through: :memberships
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
	 def new
    @account = Account.new
    @account.owner = User.new #!
  end

  def create
    @account = Account.new(account_params) # 1.
    @account.owner = User.new(user_params) # 2.

    if @account.save # 3.
      redirect_to root_url
    else
      render :new
    end
  end

  private

  def account_params
    params.require(:account).permit(:name, :subdomain)
  end

  def user_params # 4.
    params.require(:account).require(:owner_attributes).permit(:email, :first_name, :last_name, :password, :password_confirmation)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :redirect_to_subdomain # 1.

	private

  def redirect_to_subdomain
    return unless user_signed_in? # 2.

    if request.subdomain.blank? # 3.
      if current_user.accounts.any?
        redirect_to root_url(subdomain: current_user.accounts.first.subdomain)
      end
    else # 4.
      unless current_user.accounts.pluck(:subdomain).include?(request.subdomain)
        redirect_to root_url(subdomain: current_user.accounts.first.subdomain)
      end
    end
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
	before_action :authenticate_user!

	def show
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/accounts/new.html.haml
= simple_form_for @account, url: account_path do |f|
  = f.input :name
  = f.input :subdomain
  = f.fields_for :owner do |fo|
    = fo.input :email
    = fo.input :first_name
    = fo.input :last_name
    = fo.input :password
    = fo.input :password_confirmation

  = f.submit

app/views/dashboards/show.html.haml
%h1 Dashboard show

app/views/layouts/application.html.haml
!!!
%html
	%head
		%meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
		%title SaasSampleApp
		= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
		= javascript_include_tag 'application', 'data-turbolinks-track' => true
		= csrf_meta_tags
	%body
		.container
			= yield

app/views/welcome/index.html.haml
%h1 Welcome

- if current_user

- else
	= link_to 'Create new account', new_account_path, class: 'btn btn-success'